import dynamic from 'next/dynamic'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
const MyEditor = dynamic(() => import('../components/MyEditor'), { ssr: false })

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Thread Builder</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='heading'>
        <p className='title'>Thread Builder</p>
      </div>
      <MyEditor />
    </div>
  )
}
